### ISSUE TITLE
[Bug]: document pages are blank on phone app

### ISSUE THREAD

**Issue by nedwa0** [astubenbord/paperless-mobile#366] opened 2024-01-14 18:41 UTC
### What happened?

I can search for documents from phone app, but when I click on the document thumbnail, a count of the number of pages in the document appears, but each page is blank. Just upgraded To Server version 2.3.3. I am new user, so not sure if earlier version worked.

### Steps to reproduce

1 login as user with document view rights. Click on any document thumbnail. Instead of seeing document image, blank pages display 

### Paperless-ng*x Version

2.3.3

### Paperless-Mobile Version

3.2.0+404

### Device

Google Pixel Pro 6 

### Operating System Version

Android 13

### Device Locale

U.S.

### Selected Locale

None

**Comment by astubenbord** [comment] 2024-01-14 18:52
Duplicate of #350. However, I'll keep this one open since no one seems to look through closed/existing issues and this has been reported about 10 times now...

The current state of this issue is the following: There seems to be an issue with pdfx, the package I use(d) for displaying the PDF documents. I tried switching to another promising package (pdfrx) which however does not compile in the GitHub actions pipeline, which is necessary to ensure reproducible builds for F-Droid. I'm currently very busy so I don't have much time to have a deeper look into this. I'll try my best to fix this as soon as possible, but I cannot guarantee that this can quickly be fixed. If anyone is experienced with thr Android build process, feel free to hit me up at paperless-mobile@protonmail.com so this can be resolved more quickly.

**Comment by nedwa0** [comment] 2024-01-14 18:59
My apologies for not spotting it in existing issues

**Comment by Bluemeus** [comment] 2024-01-15 16:14
Thanks for this information, so i can understand why no update is available, but the bug is marked as solved. Hope you can find a solution to fix it. 

Without the preview the app feels a little sketchy and using it in daily life gets a bit inconvenient, because you have to open the document to know, if it is the right one.

On the other hand i have absolute appreciation for working on this along the way. So i love this app very much, helping me to get paperless!

**Comment by donverse** [comment] 2024-01-16 19:01
You can download a lower app version from F-Droid, that works for me until fixed

**Comment by astubenbord** [comment] 2024-01-18 20:51
I just found a fix which will hopefully resolve this. Let's just pray that the build will run...
Update: Good news, 3.2.1 is currently under review and already available on GitHub!

**Comment by donverse** [comment] 2024-01-18 21:59
Yay! I confirm it works 🥳

**Comment by Bluemeus** [comment] 2024-01-20 08:50
It works! Thank you very much!!! 👏👍🎉🍾

**Closed as completed** 2024-01-23 07:32 UTC
Labels: bug

**Comment by nedwa0** [comment] 2024-01-25 02:22
Thank you, I appreciate you fixing this issue.

Hanief

**Comment by MalteKW** [comment] 2024-03-01 10:43
Awsome, thank you for fixing it. Works again on my Pixel 7.
