### ISSUE TITLE
Can't upload documents scanned with the app

### ISSUE THREAD

**Issue by eikeja** [astubenbord/paperless-mobile#70] opened 2023-01-14 10:48 UTC
When processing the file, there is an error under "File tasks": 'str' object has no attribute 'utcoffset'.

Pixel 7 Pro, Android 13
Newest App -Version
Paperless-Version: 1.11.3

**Comment by astubenbord** [comment] 2023-01-16 22:20
Hi, this seems like it's a server side issue, see https://github.com/paperless-ngx/paperless-ngx/issues/2435

**Comment by shamoon** [comment] 2023-01-16 23:52
The other way to handle this is to pass a valid iso 8601 string (technically thats what the api expects) but the linked change should make this more flexible anyway

**Comment by astubenbord** [comment] 2023-01-16 23:59
@shamoon I already tried setting the 'created' field to '2023-01-16T23:57:02.563005Z', however, it results in the same error.

**Comment by shamoon** [comment] 2023-01-17 00:00
Odd, ok well then im glad to have the change =)

**Comment by astubenbord** [comment] 2023-01-17 00:03
Yeah, I'm starting to think that my paperless installation could be corrupt...

**Comment by astubenbord** [comment] 2023-01-17 00:07
Hm, I just tried with a fresh local docker instance and it seems to work as expected, with both iso 8601 and yyyy-MM-dd formats...

**Comment by astubenbord** [comment] 2023-02-11 12:41
@eikeja Is this resolved in the latest version?

**Comment by astubenbord** [comment] 2023-02-14 23:20
Closing as duplicate of #72

**Closed by astubenbord** 2023-02-14 23:20 UTC
Labels: bug
