### ISSUE TITLE
Saved views are not persistent

### ISSUE THREAD

**Issue by jdckr** [astubenbord/paperless-mobile#21] opened 2022-11-14 17:50 UTC
Saved views are lost when closing the app via app drawer. Aren't those stored persistent?

PS: Thanks for this great app. It has all the features I was missing from the other apps.

**Comment by astubenbord** [comment] 2022-11-14 19:53
Hi, thanks for the kind words :) 
Yes, the views are persisted on the paperless server, they directly correspond to the saved views in the paperless web client.
What exactly do you mean with 'closing the app via app drawer'? 
Do you mean logging out and logging back in?

Cheers

**Comment by jdckr** [comment] 2022-11-14 20:11
When I go to androids current running apps overview and close/kill paperless-mobile, the saved views are gone when opening the app again.
But I checked on the webserver, it shows the newly created and older views.

**Comment by astubenbord** [comment] 2022-11-14 20:16
Okay, do you get an error saying something along the lines of 'could not load saved views'?

**Comment by jdckr** [comment] 2022-11-14 20:17
No. Should this be shown as a toast?

**Comment by astubenbord** [comment] 2022-11-14 20:46
If the views were not correctly loaded then yes, otherwise I don't know the reason why they're not shown. what device/Android version and server version are you running?

**Comment by jdckr** [comment] 2022-11-14 20:47
Pixel 4a, Android 13, Paperless 1.10.0 Beta

**Comment by astubenbord** [comment] 2022-11-14 22:54
okay, I haven't used the 1.10 release yet, maybe the request format has changed, I'll report back once I've investigated the issue.

**Comment by astubenbord** [comment] 2022-11-15 17:27
What API version is shown in the app drawer?

**Comment by astubenbord** [comment] 2022-11-15 21:21
Hm, I really can't find a reason why they wouldn't load, there are no changes to the saved views in 1.10.
Would it be possible for you to debug it locally?

**Comment by sarakha63** [comment] 2022-11-15 23:49
I Can confirm on my side that saved views are saved on paperless server

And those are fetched back once the mobile app is relaunched.

@jdckr when you save a view in the app.

Do you see it in paperless webpage after ?

**Comment by jdckr** [comment] 2022-11-16 07:52
I deleted all the saved views from the server and restartet the app. After that I was able to successfully see newly created views also in the app. I compared the json before and after deletion, but couldn't see a significant difference.

**Comment by astubenbord** [comment] 2022-11-16 10:08
but there was a difference?

**Comment by jdckr** [comment] 2022-11-16 11:27
Only the value of `id` and `sort_order`
```
{"count":3,"next":null,"previous":null,"results":[{"id":14,"name":"Inbox","show_on_dashboard":true,"show_in_sidebar":true,"sort_field":"added","sort_reverse":false,"filter_rules":[{"rule_type":6,"value":"1"}]},{"id":16,"name":"Type: Rechnung","show_on_dashboard":false,"show_in_sidebar":true,"sort_field":"added","sort_reverse":true,"filter_rules":[{"rule_type":4,"value":"1"}]},{"id":15,"name":"Typ: Quittung","show_on_dashboard":false,"show_in_sidebar":true,"sort_field":"added","sort_reverse":false,"filter_rules":[{"rule_type":4,"value":"8"}]}]}
```

**Comment by astubenbord** [comment] 2022-11-16 15:08
Do you mean sort_field or sort_reverse? Maybe there's some problem with serialization (although I couldn't think of one)

**Comment by jdckr** [comment] 2022-11-16 16:04
I meant sort_reverse. In my last comment and in one of the earlier comments I added the ouput. So you should also be able to compare. I formatted the output with VSCode to be able to compare it. Maybe when comparing the raw data we can find s.th.

**Comment by astubenbord** [comment] 2022-11-18 00:22
Hm, sort reverse doesn't affect loading for me. The views are not fully supported yet, i.e. there are criteria which might be saved in a view by paperless which are currently not parsed. But this shouldn't affect the way views are parsed and saved. Would you consider this resolved?

**Comment by jdckr** [comment] 2022-11-18 08:44
I would consider this as closed as I don't know how to further reproduce/debug this. Maybe you can add a label `unconfirmed` and close it.
Maybe there was something corrupt in my paperless installation. I also had the problem with 1.9.0 that the API didn't give me a response. That's also the reason why I updated to 1.10.0 beta in the first place.

**Closed** 2022-11-19 22:37 UTC
Labels: not reproducible
