### ISSUE TITLE
[BUG] Can't log in

### ISSUE THREAD

**Issue by CharlotteCross1998** [astubenbord/paperless-mobile#249] opened 2023-08-23 09:35 UTC
**Before submitting a bug report**

- [x] I have looked through [existing issues](https://github.com/astubenbord/paperless-mobile/issues?q=is%3Aissue) and found no similar issue that is either open or has already been fixed
- [x] I have read the [troubleshooting section](https://github.com/astubenbord/paperless-mobile#troubleshooting) in the repository's README
- [x] I have tried to re-install the app, and the issue still occurs. The app is still subject to breaking changes, requiring a fresh installation or at least clearing app data after updating.

**Describe the bug**
When trying to login, cannot. Get error: type 'String' is not a subtype of type 'Map<String, dynamic>'

**To Reproduce**
1. Attempt to login
2. See error

**Expected behavior**
Should log in.

**Screenshots**
![Screenshot_20230823-102638](https://github.com/astubenbord/paperless-mobile/assets/29734551/c5f23594-591d-42ce-8bb1-93201638b8f7)

**Device Information:**
 - Device: Pixel 6 Pro
 - OS: Android 14
 - Paperless Mobile version 2.3.9
 - Paperless Server version 1.5.0 (paperless-ng)
 
**Additional Context**
App previously worked on a local install, not sure what the server version was of that but would have been the same or lower. Server user has all permissions.

**Comment by astubenbord** [comment] 2023-08-23 09:39
Hi, while I try to maintain backwards compatibility for older versions, I cannot cover all changes in the API, which are often also not properly documented. Given your server version (1.5.0, current is 1.17.0), I would _highly_ recommend you to upgrade to paperless-ngx as outlined here https://docs.paperless-ngx.com/setup/#migrating-to-paperless-ngx. Newer versions typically offer much better support and fix a lot of bugs with many new features. Also, it is much easier for me to reproduce issues. 

Cheers

**Comment by astubenbord** [comment] 2023-08-23 09:40
Closing as duplicate of https://github.com/astubenbord/paperless-mobile/issues/215

**Closed as not planned by astubenbord** 2023-08-23 09:40 UTC
Labels: duplicate

**Comment by CharlotteCross1998** [comment] 2023-09-10 16:46
Since paperless-ngx doesn't work on my server, I fixed it by simply installing 2.0.7

**Comment by astubenbord** [comment] 2023-09-11 11:56
> Since paperless-ngx doesn't work on my server, ...

How's that? Any specific reasons why it doesn't work?

**Comment by CharlotteCross1998** [comment] 2023-09-12 19:31
> > Since paperless-ngx doesn't work on my server, ...
> 
> How's that? Any specific reasons why it doesn't work?

Don't remember, was a couple months ago when I tried setting it up.

**Comment by astubenbord** [comment] 2023-09-13 08:12
>Don't remember, was a couple months ago when I tried setting it up.

Did you refer to the official migration path in the documentation? https://docs.paperless-ngx.com/setup/#migrating-to-paperless-ngx

**Comment by CharlotteCross1998** [comment] 2023-09-13 11:40
> > Don't remember, was a couple months ago when I tried setting it up.
> 
> Did you refer to the official migration path in the documentation? https://docs.paperless-ngx.com/setup/#migrating-to-paperless-ngx

It wasn't migrating, it was getting it up and running. Only -ng worked.

**Comment by thomclae33** [comment] 2023-09-16 11:21
Same issue, completely new install

**Comment by astubenbord** [comment] 2023-09-16 11:26
> Same issue, completely new install

Also on Paperless-ng?

**Comment by thomclae33** [comment] 2023-09-16 12:04
Paperless-ng works fine, but only older versions of the Android App work without the error message in this thread.

**Comment by astubenbord** [comment] 2023-09-16 12:15
> Paperless-ng works fine, but only older versions of the Android App work without the error message in this thread.

Yes, this is expected since the newer versions implement the newer API v3, which was introduced with paperless-ngx 1.14.

The amount of effort required to keep support for older versions (like paperless-ng or paperless-ngx < 1.14) is currently simply too high for me as the sole developer. Of course I'd like to maintain support for older versions, but that is (currently) not the priority since the majority of users are already using newer versions of paperless-ngx.

**Comment by thomclae33** [comment] 2023-09-16 12:29
But I run paperless-ngx 1.15? Only older version for the Android app work with my (Docker) instance.

**Comment by thomclae33** [comment] 2023-09-16 12:30
Aha! That seems to be my issue. My docker runs paperless-ng. Thank you for clarifying.
