### ISSUE TITLE
[Bug]: No preview of a document in Paperless Android app

### ISSUE THREAD

**Issue by Igor01-Tech** [astubenbord/paperless-mobile#353] opened 2024-01-09 09:17 UTC
### What happened?

There is no preview when opening a document in the Android app. But it's working inside Chrome on my Windows 11 computer.

![Screenshot_20240109-073919](https://github.com/astubenbord/paperless-mobile/assets/61701217/974bb346-037e-46be-b0b1-1d2cd445f6bd)
![Screenshot_20240109-073925](https://github.com/astubenbord/paperless-mobile/assets/61701217/2f51efc3-0e7a-4531-b06a-46724e7ff21e)

### Steps to reproduce

1. (Clean install the Android app)
2. Open the Android app (and login)
3. Touch on any document
4. touch the upper (small) preview-picture which is shown
5. the new screen appears without showing the actual document. even the correct number of pages at the buttom appear. But no actual document is shown

### Log output from the app

```shell
2024-01-09 07:28:56.824	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-09 07:28:56.825	DEBUG   --- [      AuthenticationCubit] - restoreSession           : There is nothing to restore.
2024-01-09 07:28:56.830	INFO    --- [                         ] -                          : Setting refresh rate to 90.0
2024-01-09 07:29:09.074	DEBUG   --- [      AuthenticationCubit] - login                    : Trying to log in...
2024-01-09 07:29:09.074	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Adding new user ..
2024-01-09 07:29:09.075	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Fetching bearer token from the server...
2024-01-09 07:29:09.569	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Bearer token successfully retrieved.
2024-01-09 07:29:09.571	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-09 07:29:09.643	WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-09 07:29:09.644	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-09 07:29:09.644	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Trying to fetch remote paperless user for XXXXXXXXX.
2024-01-09 07:29:09.746	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Remote paperless user successfully fetched.
2024-01-09 07:29:09.747	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Persisting user account information...
2024-01-09 07:29:09.777	DEBUG   --- [      AuthenticationCubit] - _addUser                 : User account information successfully persisted.
2024-01-09 07:29:09.777	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Persisting user app state...
2024-01-09 07:29:09.781	DEBUG   --- [      AuthenticationCubit] - _addUser                 : User state successfully persisted.
2024-01-09 07:29:10.386	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Saving user credentials inside encrypted storage...
2024-01-09 07:29:10.387	DEBUG   --- [      AuthenticationCubit] - _addUser                 : User credentials successfully saved.
2024-01-09 07:29:10.388	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Added new url to list of hosts.
2024-01-09 07:29:10.388	DEBUG   --- [      AuthenticationCubit] - login                    : User XXXXXXXXX successfully logged in.
2024-01-09 07:29:10.398	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-09 07:29:10.398	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-09 07:29:10.429	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-09 07:29:10.429	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-09 07:29:10.750	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-09 07:29:10.751	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-09 07:29:10.766	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-09 07:29:10.877	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-09 07:29:10.910	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-09 07:29:10.911	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-09 07:29:10.926	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-09 07:29:10.985	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
```

### Paperless-ng*x Version

2.3.2

### Paperless-Mobile Version

Newest

### Device

Pixel 6

### Operating System Version

14

### Device Locale

german

### Selected Locale

German

**Comment by astubenbord** [comment] 2024-01-09 09:19
Closing as duplicate of #350.

**Closed as completed** 2024-01-09 09:19 UTC
Labels: bug, duplicate
