### ISSUE TITLE
[Bug]: Camera ratio wrong on Galaxy Fold5

### ISSUE THREAD

**Issue by MaxWinterstein** [astubenbord/paperless-mobile#326] opened 2023-12-14 12:31 UTC
### What happened?

When using the App on my Galazy Fold5, the scanner shows a weird stretched image in the foto live preview and the cropping preview.

This happens in the closed as well as in the opened case.

The final scan is correct. 

### Steps to reproduce

Open the scanner - see weird ratio

### Screenshots

**Foto of a nice plate of cookies, taken with camera app for comparison:**
![Screenshot_20231214_132248_Camera](https://github.com/astubenbord/paperless-mobile/assets/5927148/ff1fa9e8-c78e-4940-8dab-2ee4742996e7)

**What the scanner preview shows:**
![Screenshot_20231214_132305](https://github.com/astubenbord/paperless-mobile/assets/5927148/9220ee42-8b41-4e63-9e09-700259a70e2e)

**What the cropping preview shows:**
![Screenshot_20231214_132316](https://github.com/astubenbord/paperless-mobile/assets/5927148/0a5b412d-1713-4f00-813c-432e1670f95d)

**After cropping:**
![Screenshot_20231214_132341](https://github.com/astubenbord/paperless-mobile/assets/5927148/b5cfddc0-f02f-41bb-8346-7f01eca1b9ed)

**Inbox view:**
![Screenshot_20231214_132534](https://github.com/astubenbord/paperless-mobile/assets/5927148/6c3b390c-1e24-4f9d-87c3-0b6aa46932d2)

All above pictures are in opened mode, in closed mode, the front screen, it is shrinked the other way:

![Screenshot_20231214_133322](https://github.com/astubenbord/paperless-mobile/assets/5927148/ddc46339-4c8d-44d5-aeb2-4ae6defdb461)

### Paperless-ng*x Version

-

### Paperless-Mobile Version

3.1.4

### Device

Galaxy Fold 5

### Operating System Version

Android 14

### Device Locale

German

### Selected Locale

German

**Comment by astubenbord** [comment] 2023-12-16 13:59
Closing as duplicate of #42 and in favor of #322

**Closed as not planned by astubenbord** 2023-12-16 13:59 UTC
Labels: bug
