### ISSUE TITLE
Grey screen when trying to add new tags or correspondents

### ISSUE THREAD

**Issue by twobrain** [astubenbord/paperless-mobile#247] opened 2023-08-10 16:56 UTC
Grey screen. Whenever trying to add a new tag or correspondent.

**Comment by astubenbord** [comment] 2023-08-13 16:53
Closing as duplicate of #233.

Please note that I didn't get to publish an update with this fix yet, it will probably take another week or two until I have more time on my hands.

**Closed as completed by astubenbord** 2023-08-13 16:53 UTC
Labels: duplicate
