### ISSUE TITLE
[Bug]: Documents can't be oped - Download works

### ISSUE THREAD

**Issue by philsch85** [astubenbord/paperless-mobile#354] opened 2024-01-09 21:17 UTC
### What happened?

I am not able to open already stored or new Documents. The Preview is visble, but after selecting it, there is only 1 or x blank pages

### Steps to reproduce

Select a random File and try to open it by selecting the Thumpnail

### Screenshots

![Screenshot_20240109_221332](https://github.com/astubenbord/paperless-mobile/assets/152910364/77a751cc-0cea-4522-9ed8-5463ad961792)

### Paperless-ng*x Version

2.3.2

### Paperless-Mobile Version

3.2.0+404

### Device

Samsung Galaxy s 20

### Operating System Version

13

### Device Locale

German

### Selected Locale

None

**Comment by astubenbord** [comment] 2024-01-09 21:50
Closing as duplicate of #350. It's already fixed but there is an issue with the pipeline which I cannot debug at the moment.

**Closed as completed** 2024-01-09 21:50 UTC
Labels: bug
