### ISSUE TITLE
Scanner shows camera stretched out

### ISSUE THREAD

**Issue by qwaykee** [astubenbord/paperless-mobile#299] opened 2023-11-09 18:03 UTC
Here is what the scanner shows
![Screenshot_2023-11-09-18-55-05-077_de astubenbord paperless_mobile](https://github.com/astubenbord/paperless-mobile/assets/43087986/d68fd927-a01c-4641-94e4-96df868e54f9)
And what my camera shows
![Screenshot_2023-11-09-18-55-12-555_com android camera](https://github.com/astubenbord/paperless-mobile/assets/43087986/dfd8aaad-0ed4-4522-81fe-61d2a63e1bb2)
I'm using a Redmi 10C which has a 6,71" screen, also I tried to put the native camera in full mode (the picture is the same size as the whole screen) and it doesn't change anything

Also not really an issue but I think it's still useful to ask, is it normal that I have to wait a few minutes before the first connection to the server works? The server is hosted on a local computer.

**Comment by astubenbord** [comment] 2023-11-11 09:09
Closing as duplicate of #42

**Closed as completed** 2023-11-11 09:09 UTC
Labels: bug, duplicate
