### ISSUE TITLE
[Bug]: App hangs on splash screen

### ISSUE THREAD

**Issue by thumDer** [astubenbord/paperless-mobile#266] opened 2023-10-09 16:20 UTC
### What happened?

App hangs on splash screen logo, even after force stop. The only way to make it work again is to delete app data.

### Steps to reproduce

It cannot be really reproduced, the app works for a while, and just stops.

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

3.0.3 beta

**Comment by astubenbord** [comment] 2023-10-09 16:25
Hi. 

What's the locale of your device?

**Comment by thumDer** [comment] 2023-10-09 20:11
<img src="https://user-images.githubusercontent.com/54556708/273688344-f05d9b2d-cdc7-436a-940b-333c8165205c.jpg" width="400">

**Comment by astubenbord** [comment] 2023-10-09 21:08
Any way you could hook up the phone to your computer and run `flutter logs` or `adb logcat | grep flutter` while starting the app? Otherwise there is not much I can do to debug if I don't know how to reproduce this issue :/

Thanks

**Comment by Dtrieb** [comment] 2023-10-10 10:38
Same here on a German Pixel 7 pro.

**Comment by Dtrieb** [comment] 2023-10-10 10:45
@astubenbord

But, if I delete the Cache and App Data I could start the start Dialog again.

Then everything run fine.

**Comment by astubenbord** [comment] 2023-10-10 10:48
Hm, any way you guys could get me some logs? I cannot reproduce this. I think I'll have to write the logs to a file on the device in the future so less technical users may be able to quickly access them, which helps a lot in debugging these random crashes.

**Comment by Schrolli91** [comment] 2023-10-11 05:38
Same here after joining the beta program - have deleted all appdata, now it runs again (3.0.6+53)

**Comment by thumDer** [comment] 2023-10-11 10:06
> Any way you could hook up the phone to your computer and run `flutter logs` or `adb logcat | grep flutter` while starting the app? Otherwise there is not much I can do to debug if I don't know how to reproduce this issue :/
> 
> Thanks

Never did that before, but will try once I'll have some time, and get back to you! I'll have to wait until it happens again.

**Comment by ITCMD** [comment] 2023-10-12 13:49
Just joined the beta program. On first launch it's just hung on the startup logo. Clearing cache did not fix it but clearing data did. I was unable to get any logs since the app would not open before doing this.

**Comment by astubenbord** [comment] 2023-10-12 16:38
I'm almost done with a new update in which the logs are written to a file and generally much more expressive. Maybe update and once it happens, send me the logs? I assume that it's an issue with hive and a change in the database schema between 2.x and 3.x.

**Comment by fw-wlsr** [comment] 2023-11-14 10:53
Hello ;-)

I also have this problem. Now at least the second time (Huawei P30, EMUI 12.0)
I'm not 100% sure if this is helpful, but I found this log file here: 

/Android/data/de.astubenbord.paperless_mobile/files/documents/logs:

[2023-11-14.txt](https://github.com/astubenbord/paperless-mobile/files/13347890/2023-11-14.txt)

**Comment by amo13** [comment] 2023-11-16 19:08
Same for me, hang and crash on startup. Only the splash screen shows. 
<details>
<summary>Here my logs:</summary>

```
1700160833.456 10222  8853  8853 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10222; state: ENABLED
1700160833.463 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.arm64_v8a.dm': No such file or directory
1700160833.463 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.arm64_v8a.dm': No such file or directory
1700160833.463 10222  8853  8853 W aperless_mobile: Entry not found
1700160833.463 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.de.dm': No such file or directory
1700160833.463 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.de.dm': No such file or directory
1700160833.463 10222  8853  8853 W aperless_mobile: Entry not found
1700160833.463 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.en.dm': No such file or directory
1700160833.463 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.en.dm': No such file or directory
1700160833.464 10222  8853  8853 W aperless_mobile: Entry not found
1700160833.464 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.xxhdpi.dm': No such file or directory
1700160833.464 10222  8853  8853 W ziparchive: Unable to open '/data/app/~~vXwskuzUggYcmF4jlHrKCA==/de.astubenbord.paperless_mobile-lNCkdJvo7LhZon8s7HLE_A==/split_config.xxhdpi.dm': No such file or directory
1700160833.464 10222  8853  8853 W aperless_mobile: Entry not found
1700160833.467 10222  8853  8853 W aperless_mobile: JIT profile information will not be recorded: profile file does not exist.
1700160833.467 10222  8853  8853 W aperless_mobile: JIT profile information will not be recorded: profile file does not exist.
1700160833.467 10222  8853  8853 W aperless_mobile: JIT profile information will not be recorded: profile file does not exist.
1700160833.467 10222  8853  8853 W aperless_mobile: JIT profile information will not be recorded: profile file does not exist.
1700160833.473 10222  8853  8853 V GraphicsEnvironment: ANGLE Developer option for 'de.astubenbord.paperless_mobile' set to: 'default'
1700160833.474 10222  8853  8853 V GraphicsEnvironment: ANGLE GameManagerService for de.astubenbord.paperless_mobile: false
1700160833.474 10222  8853  8853 V GraphicsEnvironment: Updatable production driver is not supported on the device.
1700160833.475 10222  8853  8853 D NetworkSecurityConfig: No Network Security Config specified, using platform default
1700160833.475 10222  8853  8853 D NetworkSecurityConfig: No Network Security Config specified, using platform default
1700160833.490 10222  8853  8853 W aperless_mobile: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
1700160833.490 10222  8853  8853 W aperless_mobile: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
1700160833.490 10222  8853  8853 W aperless_mobile: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
1700160833.523 10222  8853  8853 W aperless_mobile: type=1400 audit(0.0:14617): avc: denied { read } for name="max_map_count" dev="proc" ino=27968955 scontext=u:r:untrusted_app:s0:c222,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 ppid=917 pcomm="main" pgid=917 pgcomm="main" app=de.astubenbord.paperless_mobile
1700160833.533 10222  8853  8853 I AdrenoGLES-0: QUALCOMM build                   : db3d445dbc, Ia06b22fa1a
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Build Date                       : 10/04/21
1700160833.533 10222  8853  8853 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.16
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Local Branch                     :
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Remote Branch                    :
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Remote Branch                    :
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Reconstruct Branch               :
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
1700160833.533 10222  8853  8853 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
1700160833.537 10222  8853  8853 I AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
1700160833.560 10222  8853  8853 D CompatibilityChangeReporter: Compat change id reported: 193247900; UID 10222; state: ENABLED
1700160833.581 10222  8853  8853 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10222; state: DISABLED
1700160833.585 10222  8853  8872 W Parcel  : Expecting binder but got null!
1700160833.598 10222  8853  8877 I flutter : Logging files to /storage/emulated/0/Android/data/de.astubenbord.paperless_mobile/files/documents/logs/2023-11-16.log.
1700160833.609 10222  8853  8872 E OpenGLRenderer: Unable to match the desired swap behavior.
1700160833.623 10222  8853  8877 I flutter : 2023-11-16 19:53:53.623 ERROR   --- [                         ] - main                     : An unexpected error occurred
1700160833.626 10222  8853  8877 I flutter : ---BEGIN ERROR---
1700160833.626 10222  8853  8877 I flutter : HiveError: Cannot read, unknown typeId: 132. Did you forget to register an adapter?
1700160833.627 10222  8853  8877 I flutter : ---END ERROR---
1700160833.627 10222  8853  8877 I flutter : ---BEGIN STACKTRACE---
1700160833.627 10222  8853  8877 I flutter : #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
1700160833.627 10222  8853  8877 I flutter : #1      LocalUserAppStateAdapter.read (package:paperless_mobile/core/database/tables/local_user_app_state.g.dart:17)
1700160833.627 10222  8853  8877 I flutter : #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
1700160833.627 10222  8853  8877 I flutter : #3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
1700160833.627 10222  8853  8877 I flutter : #4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
1700160833.627 10222  8853  8877 I flutter : #5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
1700160833.627 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.628 10222  8853  8877 I flutter : #6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
1700160833.628 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.628 10222  8853  8877 I flutter : #7      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
1700160833.628 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.628 10222  8853  8877 I flutter : #8      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
1700160833.628 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.628 10222  8853  8877 I flutter : #9      _initHive (package:paperless_mobile/main.dart:110)
1700160833.628 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.628 10222  8853  8877 I flutter : #10     main.<anonymous closure> (package:paperless_mobile/main.dart:155)
1700160833.628 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.628 10222  8853  8877 I flutter : ---END STACKTRACE---
1700160833.628 10222  8853  8877 I flutter : 2023-11-16 19:53:53.623 ERROR   --- [                         ] - main                     : An unexpected error occurred
1700160833.629 10222  8853  8877 I flutter : ---BEGIN ERROR---
1700160833.629 10222  8853  8877 I flutter : HiveError: Cannot read, unknown typeId: 132. Did you forget to register an adapter?
1700160833.629 10222  8853  8877 I flutter : ---END ERROR---
1700160833.630 10222  8853  8877 I flutter : ---BEGIN STACKTRACE---
1700160833.630 10222  8853  8877 I flutter : #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
1700160833.630 10222  8853  8877 I flutter : #1      LocalUserAppStateAdapter.read (package:paperless_mobile/core/database/tables/local_user_app_state.g.dart:17)
1700160833.630 10222  8853  8877 I flutter : #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
1700160833.630 10222  8853  8877 I flutter : #3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
1700160833.630 10222  8853  8877 I flutter : #4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
1700160833.630 10222  8853  8877 I flutter : #5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
1700160833.630 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.630 10222  8853  8877 I flutter : #6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
1700160833.630 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.630 10222  8853  8877 I flutter : #7      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
1700160833.630 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.630 10222  8853  8877 I flutter : #8      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
1700160833.630 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.630 10222  8853  8877 I flutter : #9      _initHive (package:paperless_mobile/main.dart:110)
1700160833.630 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.630 10222  8853  8877 I flutter : #10     main.<anonymous closure> (package:paperless_mobile/main.dart:155)
1700160833.630 10222  8853  8877 I flutter : <asynchronous suspension>
1700160833.631 10222  8853  8877 I flutter : ---END STACKTRACE---
1700160838.839 10222  8853  8900 D ProfileInstaller: Installing profile for de.astubenbord.paperless_mobile
```

</details>
<details>
<summary>And also:
</summary>

```
ANR in de.astubenbord.paperless_mobile (de.astubenbord.paperless_mobile/.MainActivity)
PID: 8853
Reason: Input dispatching timed out (Application does not have a focused window)
Parent: de.astubenbord.paperless_mobile/.MainActivity
ErrorId: 719917e1-2578-4d3d-8f92-a0ee61c35622
Frozen: false
Load: 0.0 / 0.22 / 0.64
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.01 avg300=0.00 total=82046355
full avg10=0.00 avg60=0.00 avg300=0.00 total=26448123
----- End output from /proc/pressure/memory -----
CPU usage from 0ms to 5191ms later (2023-11-16 19:58:07.441 to 2023-11-16 19:58:12.632):
  ***redacted***
25% TOTAL: 13% user + 10% kernel + 0.3% iowait + 0.7% irq + 0.2% softirq
CPU usage from 70ms to 461ms later (2023-11-16 19:58:07.511 to 2023-11-16 19:58:07.902) with 99% awake:
  ***redacted***
  7.3% 8853/de.astubenbord.paperless_mobile: 3.6% user + 3.6% kernel / faults: 7 minor
    3.6% 8853/aperless_mobile: 3.6% user + 0% kernel
    3.6% 8872/RenderThread: 0% user + 3.6% kernel
  2.7% 562/crtc_event:137: 0% user + 2.7% kernel
  3.9% 23056/kworker/u16:10-memlat_wq: 0% user + 3.9% kernel
20% TOTAL: 9.1% user + 10% kernel + 0.6% irq
Completed ANR of de.astubenbord.paperless_mobile in 5258ms, latency 1ms
```

</details>

I'm on Android 13 with official LineageOS (for microG), without magisk or any other rooting method.

**Comment by astubenbord** [comment] 2023-11-16 20:07
Thanks for your inputs. I think that the bytes from hive are incorrectly consumed, since there is no type adapter with id 132. 
Is there a pattern when this happens so I can try to reproduce this issue? 

@amo13 did this occur after an update or randomly?

**Comment by amo13** [comment] 2023-11-16 20:39
Not quite sure, but I think it is since the lässt update a few days ago.

**Comment by Schrolli91** [comment] 2023-11-17 05:55
> Is there a pattern when this happens so I can try to reproduce this issue?

For me this happened only once, if i updated from normal version to the beta program.
After clearing the Appdata all was fine again and never happend.

**Comment by amo13** [comment] 2023-11-17 06:55
I should have thought of that. Clearing the app data worked for me too, thanks!

**Comment by astubenbord** [comment] 2023-11-18 18:39
Yeah, this is somewhat expected since the db scheme has changed from 2.x to 3.x.

**Comment by Fischje** [comment] 2023-11-20 09:54
Same here, German OnePlus 6T. Did a clear data and cache and now it works.

**Comment by astubenbord** [comment] 2023-12-12 22:31
I'll close this for now. If you encounter this again (after having performed a fresh installation) feel free to reopen.

**Closed as completed by astubenbord** 2023-12-12 22:31 UTC
Labels: bug
