### ISSUE TITLE
[Bug]: Can't open document viewer

### ISSUE THREAD

**Issue by plckr** [astubenbord/paperless-mobile#359] opened 2024-01-10 23:44 UTC
### What happened?

Describe what happened!

### Steps to reproduce

1. Open a document
2. Click on the preview thumbnail

### Log output from the app

```shell
When trying to full preview the document, the document doesn't load.
Before I was able to get preview loaded
```

### Screenshots

![Screenshot_20240110-234207](https://github.com/astubenbord/paperless-mobile/assets/11768109/963544fe-ef16-4399-bce5-ac43abb231bc)

### Paperless-ng*x Version

2.3.2

### Paperless-Mobile Version

3.2.0+404

### Device

Samsung S21

### Operating System Version

Android 11

### Device Locale

english

### Selected Locale

None

**Comment by astubenbord** [comment] 2024-01-11 07:25
Closing as duplicate of #350.

**Closed as completed** 2024-01-11 07:25 UTC
Labels: bug, duplicate
