### ISSUE TITLE
[Bug]: Document Preview on Android App

### ISSUE THREAD

**Issue by StefanPeesel** [astubenbord/paperless-mobile#370] opened 2024-01-17 06:46 UTC
### What happened?

The Document Preview in the Android App shows only a black screen for each Page of the Document. The Web Preview ist still okay.

### Steps to reproduce

Just click the Document Preview 

### Screenshots

![Uploading Screenshot_20240117-074201.png…]()

### Paperless-ng*x Version

2.0.1

### Paperless-Mobile Version

3.2.0+404

### Device

Pixel 7 Pro

### Operating System Version

Android 14

### Device Locale

Germany

### Selected Locale

German

**Comment by astubenbord** [comment] 2024-01-17 07:05
Duplicate of #366

**Closed as completed** 2024-01-17 07:05 UTC
Labels: bug
