### ISSUE TITLE
[Bug]: Keine Vorschau in der App möglich 

### ISSUE THREAD

**Issue by laz198161** [astubenbord/paperless-mobile#365] opened 2024-01-12 23:48 UTC
### What happened?

Keine Vorschau der Dokumente möglich 

### Steps to reproduce

Ok

### Log output from the app

```shell
2024-01-13 00:11:11.255	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-13 00:11:11.256	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-13 00:11:11.263	INFO    --- [                         ] -                          : Setting refresh rate to 60.0
2024-01-13 00:11:11.633	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-13 00:11:11.634	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-13 00:11:11.634	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-13 00:11:11.983	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-13 00:11:11.984	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-13 00:11:12.094	WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-13 00:11:12.094	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-13 00:11:12.094	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-13 00:11:12.243	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-13 00:11:12.243	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-13 00:11:12.245	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-13 00:11:12.275	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:11:12.276	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:11:12.870	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:11:13.371	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:11:13.373	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:11:13.563	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:37:38.062	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-13 00:37:38.063	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-13 00:37:38.070	INFO    --- [                         ] -                          : Setting refresh rate to 60.0
2024-01-13 00:37:38.450	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-13 00:37:38.451	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-13 00:37:38.451	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-13 00:37:38.517	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-13 00:37:38.517	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-13 00:37:38.657	WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-13 00:37:38.658	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-13 00:37:38.658	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-13 00:37:38.802	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-13 00:37:38.802	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-13 00:37:38.804	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-13 00:37:38.831	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:37:38.833	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:37:39.538	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:37:39.902	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:37:39.902	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:37:40.040	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:38:08.836	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:38:09.148	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:38:38.836	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:38:39.166	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:39:35.178	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-13 00:39:35.178	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-13 00:39:35.186	INFO    --- [                         ] -                          : Setting refresh rate to 60.0
2024-01-13 00:39:35.531	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-13 00:39:35.531	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-13 00:39:35.531	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-13 00:39:35.606	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-13 00:39:35.606	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-13 00:39:35.663	WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-13 00:39:35.664	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-13 00:39:35.664	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-13 00:39:35.820	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-13 00:39:35.821	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-13 00:39:35.822	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-13 00:39:35.843	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:39:35.845	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:39:36.467	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:39:36.713	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:39:36.714	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:39:36.910	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:40:17.557	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-13 00:40:17.558	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-13 00:40:17.565	INFO    --- [                         ] -                          : Setting refresh rate to 60.0
2024-01-13 00:40:17.923	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-13 00:40:17.924	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-13 00:40:17.924	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-13 00:40:18.007	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-13 00:40:18.007	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-13 00:40:18.063	WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-13 00:40:18.063	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-13 00:40:18.064	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-13 00:40:18.200	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-13 00:40:18.201	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-13 00:40:18.202	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-13 00:40:18.220	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:40:18.222	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:40:18.795	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:40:19.072	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:40:19.073	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-13 00:40:19.219	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-13 00:40:45.177	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Loading suggestions for document 1295...
2024-01-13 00:40:48.226	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-13 00:40:48.624	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-13 00:40:59.071	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Found 3 suggestions for document 1295.
```

### Paperless-ng*x Version

2.3.3

### Paperless-Mobile Version

3.2

### Device

Xiaomi 11T Pro

### Operating System Version

Android 13

### Device Locale

German

### Selected Locale

None

### Additional Context

J

**Comment by sowaco** [comment] 2024-01-13 12:32
I can confirm this problem with following setup:

**Paperless-ng*x Version**
2.3.3

**Paperless-Mobile Version**
3.2+404

**Device**
Xiaomi MI 8 Lite

**Operating System Version**
Android 10

**Device Locale**
German

This Issue seems to be a duplicate of https://github.com/astubenbord/paperless-mobile/issues/363

**Comment by astubenbord** [comment] 2024-01-14 18:45
Closing as duplicate of #350

**Closed as completed by astubenbord** 2024-01-14 18:45 UTC
Labels: bug
