### ISSUE TITLE
[Feature]: Swipe option between footer tabs

### ISSUE THREAD

**Issue by feuerwasser85** [astubenbord/paperless-mobile#298] opened 2023-11-09 12:03 UTC
### Description

In an older version we had the option to swipe between the footers in the app. This option is no longer available in the latest version. It would be convenient to have a toggle button in the settings menu to enable the swipe option.
Thanks!

**Comment by astubenbord** [comment] 2023-11-09 12:15
What exactly are you referring to with footers?

**Comment by feuerwasser85** [comment] 2023-11-09 12:42
![image](https://github.com/astubenbord/paperless-mobile/assets/10442073/e7ba45fd-64cb-4686-989e-9d58a6719a2b)
I'm referring to the five icons on the bottom. In an older version it was possible to swipe between these so that you could access documents, scanner, labels and inbox easily with 1-3 swipes.

**Comment by astubenbord** [comment] 2023-11-11 17:39
I didn't even know that was possible, I'll see what I can do.

**Comment by astubenbord** [comment] 2023-12-12 22:38
Unfortunately I could not reproduce this on older versions on my device. I also don't think this is an intended feature (even if it may be useful to some) by neither the flutter material library nor the material 3 specification. I'll close this as not planned since I also don't know how this behavior could be "restored" without major implementation overhead. Sorry :/

**Closed as not planned by astubenbord** 2023-12-12 22:38 UTC
Labels: enhancement, not reproducible
