### ISSUE TITLE
[Bug]: White page when creating a new correspondent during upload/scan

### ISSUE THREAD

**Issue by jabdoa2** [astubenbord/paperless-mobile#285] opened 2023-10-19 19:58 UTC
### What happened?

When I upload a document and try to add a correspondent on the upload page the app opens a white popup and nothing more happens. I am using Android with German local. Creating correspondents via the "tags" tab works fine in the app.

### Steps to reproduce

1. Upload or scan document
2. Enter something invalid to the correspondent field
3. Press Add new correspondent link
4. White popup appears.

### Log output from the app

```shell
Let me know if you need this.
```

### Screenshots

![Screenshot_20231019-155447](https://github.com/astubenbord/paperless-mobile/assets/557540/2daab16b-f2f6-48b8-997c-da5f3532eb1d)

### Paperless-ng*x Version

1.17.4 (API v3)

### Paperless-Mobile Version

2.3.9+44

### Device

Google Pixel 6

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

German

### Additional Context

None.

**Comment by astubenbord** [comment] 2023-10-19 20:11
Closing as duplicate of #233. Please make sure you look through existing and also closed issues :)

This is already fixed in the new version (3.0.*), you can get access by either joining the open beta in google play or download the apk from the releases here on github directly. 

Cheers

**Closed as completed by astubenbord** 2023-10-19 20:11 UTC
Labels: bug, duplicate
