### ISSUE TITLE
[BUG] Empty settings page

### ISSUE THREAD

**Issue by SpicyWasab** [astubenbord/paperless-mobile#122] opened 2023-02-23 21:55 UTC
**Describe the bug**
The Application Settings page is empty.

**To Reproduce**
1. Open the app
2. Click on the side menu (drawer)
3. Go to Settings
4. Click on APplication

**Expected behavior**
New to this app, but I think it shouldn't be empty.

**Device Information:**
 - Device: [e.g. Samsung Galaxy A51]
 - OS: [e.g. Android 12]
 - Paperless Mobile version : 2.0.6+23
 - Paperless Server version : 1.13.0

**Additional context**
It's already kinda reported in this one opened an hour ago (https://github.com/astubenbord/paperless-mobile/issues/121#issuecomment-1442371938) ; I'm just reporting it for the record, and 
also to say that I didn't really have the occasion to try this app (I'm new to paperless-ngx, just a few hours ago, and I already spent the whole week scanning parts of my documents with vFlat), but the app looks incredible. Like I don't think I already used an open-source app that looked so nice before. There's a lot of cool little animations as well, that's so nice. Thanks for the work c:

**Comment by astubenbord** [comment] 2023-02-23 21:57
Thanks for the kind words :) 

The grey screen shows that an error occurred on that route. What's your system language?

**Comment by SpicyWasab** [comment] 2023-02-23 22:26
You're welcome, but still thank you xD

It's french. I'm gonna try with english to see if it changes anything.

**Comment by SpicyWasab** [comment] 2023-02-23 22:30
Alright, changed the language to English (US) in system settings and restarted the app, but it's still a grey screen. I'm restarting to see if it changes anything, but I don't think it will.

Btw, now that I'm paying attention to the language, I'm really unsure about what language was displayed before, but I think it was english as well.

**Comment by astubenbord** [comment] 2023-02-23 22:32
Okay, I was just wondering because as indicated in #121 it could have to do with language. Could you try to reinstall the app and see if the problem still occurs? Thanks

**Comment by SpicyWasab** [comment] 2023-02-23 22:53
Reversed to french, removed the app and reinstalled.
It's still gray. The app is in english. (is there a french version ?)

**Comment by astubenbord** [comment] 2023-02-23 23:06
So I just looked at the code and I'm pretty confident I know what the problem is. 

We moved to a new localization platform (Crowdin) which handles some things slightly different. Point is, that there is a French translation now, for which code is automatically generated. All strings that have not yet been translated will default to English, that's why your app appears in English. But your language settings default to the system language if a translation exists, which it does for French. 
Now, the application settings page tries to map the language tag "fr" to a language name, here "Français", which however does not yet exist in the app at version 2.0.6 since I forgot to include it in the option.
And that's where the error comes from (essentially the app tries to index a map with a non-existent key). If I ran the app in debug mode with your phone the greyed out screen would actually be red with the error message written in yellow.

I'll try to fix it either today or tomorrow.

**Comment by cgfm** [comment] 2023-04-21 17:21
I've the same issue with a slightly different configuration.

### Device Information:
> Device: Google Pixel 5
> OS: Android 13 - LineageOS 20.0
> Paperless Mobile version : 2.1.0+2027
> Paperless Server version : 1.14.0-beta.rc1

### Additional context
In addition to the described behaviour every tab in "Labels" except the first one is empty.
Also the Inbox is empty even though it shows 7 new documents in the icon.

**Comment by rubenixnagios** [comment] 2023-04-28 05:04
Just updated server & app (had same behavior as @SpicyWasab on prior install)
Now with following config I can reach the settings page but cannot change app language.
Would be nice to change app language itself. ATM app shows up in english language, not a problem for me but it is for my partner, made catalan translation for paperless mobile & would love to swtich language in settings.

**Device & App info:**
- Device: Redmi Note 8 Pro Android 11
- Paperless Mobile: 1.14.1+12 (just installed)
- Paperless Server Version: Paperless-ngx 1.14.2 (just updated)
- System Language: spanish

**Settings**
- Aplication --> Blank page
- Security --> Working (also can set up Biometric Access)
- Storage --> Working

**Comment by astubenbord** [comment] 2023-04-28 07:04
Okay I'll have a look today, I haven't tested the app with 1.14.1, maybe some things have changed there. Did you perform a fresh install of the app? Might help to clear app data

**Comment by cgfm** [comment] 2023-04-28 08:17
Yes I did. I even tried the app store version and the version from GitHub   
  
  

  

      
  
  
>

**Comment by astubenbord** [comment] 2023-04-28 08:25
Also with the new beta?

**Comment by rubenixnagios** [comment] 2023-04-28 09:36
> 

is it open to everyone? Cannot find a way to join from the play store

**Comment by rubenixnagios** [comment] 2023-04-28 09:37
sorry, joined just now! only available from android app

**Comment by rubenixnagios** [comment] 2023-04-28 09:47
beta tester now!!
if I could change language from my phone it will be lovely, also issue opened with server side paperless-ngx to assign owner & storage path from email rule ... then It will be a perfect app 4 my use case!!! indeed its a loverly work already!!!

**Comment by astubenbord** [comment] 2023-04-28 09:51
So does it work now?
And you mean that the app syncs the language with your phone?

I will work on the new permissions update soon, but it will take some time as it's a huge update.

**Comment by rubenixnagios** [comment] 2023-04-28 09:53
nope, just tested and it does not work.

in my case it shows app in polish language (i think)

will do a clean install and report back; gimme a sec

**Comment by rubenixnagios** [comment] 2023-04-28 09:59
did a fresh install
paperless mobile 2.1.0+27 cannot set language (blank page on settings)

**Comment by astubenbord** [comment] 2023-04-28 10:01
Seems like you have not yet joined the beta, the newest beta version is 2.2.0+28, which is where all new features are in. Please check again if you joined the beta :)

**Comment by rubenixnagios** [comment] 2023-04-28 10:42
![imatge](https://user-images.githubusercontent.com/72105987/235123717-8fe2bf77-74bb-454a-b7e7-b4fc2e651393.png)
I installed this just now
had to clear cache, uninstall & reboot phone to get 2.1.0+28
It works!! nice job man; so happy now; catalan translation on place!! thanks so much for your efforts!!

**Comment by cgfm** [comment] 2023-04-28 19:40
> Also with the new beta? You have to explicitly join it on the play store page.

I'm now in the beta. I've version 2.2.0+28 now and the settings page works but all other errors still occur. All labels but the first tab correspondent say nothing created jet and the Inbox says new items in the icon but only shows a placeholder.

**Comment by astubenbord** [comment] 2023-04-28 20:31
Hm, have you already tried to restart your paperless server and clear the app data?

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 28. Apr. 2023, 21:40, schrieb Christian Meiners :

**Comment by cgfm** [comment] 2023-04-29 07:35
Several times 😕

**Comment by carnager** [comment] 2023-06-09 08:04
For me it's the other way around. Latest stable version (Installed via f-droid) works fine, but beta version shows an empty settings page.

**Comment by astubenbord** [comment] 2023-06-09 09:17
Hm, I keep reading about the F-Droid version, I hope I didn't miss something but to my knowledge there is no official apk published on F-Droid yet. 
Anyway, please always provide your paperless-ngx version and the app version (found in the App Drawer > About this app), otherwise it's essentially impossible to debug and reproduce.

Thanks

**Comment by powerpaul17** [comment] 2023-06-09 09:35
I checked and you're right, I have it through https://apt.izzysoft.de/fdroid/repo Don't know how they get your release but I guess through github..

**Comment by astubenbord** [comment] 2023-06-09 09:36
Ah nvm, it's izzy's repo, I didn't know you could add that to fdroid.

**Comment by astubenbord** [comment] 2023-06-10 14:05
Is this still occurring in the latest version (2.3.3)?

**Comment by powerpaul17** [comment] 2023-06-10 14:19
No, settings page is working now.. 🙂

**Comment by astubenbord** [comment] 2023-06-10 14:20
Okay nice, then closing as completed :)

**Closed by astubenbord** 2023-06-10 14:20 UTC
Labels: bug
