### ISSUE TITLE
[Bug]: Gray Page when trying to create new corespondant from search

### ISSUE THREAD

**Issue by Momolem** [astubenbord/paperless-mobile#297] opened 2023-11-05 13:05 UTC
### What happened?

When I search for a correspondant and none is found. I try to create a new one with the button that is shown. A gray screen opens

### Steps to reproduce

1. Edit Document
2. Change Correspondant
3. Search for one that doesn't exist
4. Press New Correspondant

### Screenshots

![Screenshot_20231105-135326~2](https://github.com/astubenbord/paperless-mobile/assets/23556018/0bb50bae-b5a1-4bad-ac5f-4e88d23309ec)
![Screenshot_20231105-140005](https://github.com/astubenbord/paperless-mobile/assets/23556018/acc8af98-8965-4399-821a-c845d24c19e9)

### Paperless-ng*x Version

1.17.4

### Paperless-Mobile Version

2.3.9+44

### Device

Google Pixel 7

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

German

### Additional Context

If you need any further information, feel free to contact me

**Comment by ryanwinter** [comment] 2023-11-05 17:22
Seeing the same issue when creating a tag.

**Comment by ryanwinter** [comment] 2023-11-05 17:23
![Screenshot_20231105-092238](https://github.com/astubenbord/paperless-mobile/assets/10238039/79f1da62-9d17-4ce7-8f38-eb83607cf8b4)

**Comment by astubenbord** [comment] 2023-11-06 08:21
Closing as duplicate of #247 and #233

**Closed as completed by astubenbord** 2023-11-06 08:21 UTC
Labels: duplicate
