### ISSUE TITLE
[Bug]: pdf-file does not show up in mobile app

### ISSUE THREAD

**Issue by Chlorgas** [astubenbord/paperless-mobile#360] opened 2024-01-11 19:54 UTC
### What happened?

If I click on a random file a blank page with the document title is shown instead of the document itself.

I run papless-ngx ([https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx](https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx)) as docker (engine 20.10.24) on unraid (v6.12.3)

### Steps to reproduce

1. open the app
2. select "Dokumente" at the navigation panel at the bottom
3. click on random document

### Log output from the app

```shell
2024-01-11 20:39:45.167	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:39:45.267	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:39:49.092	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2024-01-11 20:39:49.092	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Verifying user identity...
2024-01-11 20:39:49.098	INFO    --- [                         ] -                          : Setting refresh rate to 120.00000762939453
2024-01-11 20:39:51.347	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Identity successfully verified.
2024-01-11 20:39:51.347	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2024-01-11 20:39:51.591	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2024-01-11 20:39:51.592	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2024-01-11 20:39:51.592	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2024-01-11 20:39:51.624	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2024-01-11 20:39:51.624	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2024-01-11 20:39:51.650	WARNING --- [      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-11 20:39:51.650	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2024-01-11 20:39:51.650	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2024-01-11 20:39:51.695	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2024-01-11 20:39:51.695	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2024-01-11 20:39:51.696	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2024-01-11 20:39:51.703	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 20:39:51.703	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:39:51.857	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 20:39:51.910	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:39:51.911	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 20:39:51.987	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 20:39:55.303	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2024-01-11 20:39:55.549	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2024-01-11 20:40:21.721	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:40:21.825	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:40:51.720	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:40:51.810	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:41:21.733	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:41:21.867	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:41:51.707	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:41:51.803	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:45:22.253	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:45:22.364	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:45:52.231	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:45:52.392	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:46:37.099	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:46:37.216	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2024-01-11 20:47:07.098	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2024-01-11 20:47:07.201	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
```

### Screenshots

![Screenshot_20240111-204605](https://github.com/astubenbord/paperless-mobile/assets/28477227/8e4a023a-6c79-4ea2-8244-6be4e3a02fe0)

### Paperless-ng*x Version

2.3.3

### Paperless-Mobile Version

3.2.0

### Device

Google Pixel 8

### Operating System Version

Android 14

### Device Locale

german

### Selected Locale

German

**Comment by astubenbord** [comment] 2024-01-11 20:14
Closing as duplicate of #350

**Closed as completed by astubenbord** 2024-01-11 20:14 UTC
Labels: bug, duplicate
