### ISSUE TITLE
[Bug]: Document is not loaded, blank screen

### ISSUE THREAD

**Issue by lied** [astubenbord/paperless-mobile#352] opened 2024-01-07 18:47 UTC
### What happened?

When opening a document the preview of the PDF is displayed correctly. Once I click on the preview a black window with page selector is displayed.

It seems that a incompatible PDF viewer is used when opening the document. I tried it on my wife's phone and mine, beta version and stable - everytime I only see the blank page.

Is there a hidden option to select the PDF viewer to display the PDF? I currently use Google drive as default PDF viewer on my phone 

### Steps to reproduce

1. Click on any document preview
2. See the blank page

### Log output from the app

```shell
No relevant log output
```

### Screenshots

![Screenshot_20240107-194238](https://github.com/astubenbord/paperless-mobile/assets/556083/3f7da20f-3fd2-465b-8e15-3e6a32249a90)

![Screenshot_20240107-194228](https://github.com/astubenbord/paperless-mobile/assets/556083/86b728f2-f085-4cba-bc17-6cc969a5f9d1)

### Paperless-ng*x Version

2.2.1

### Paperless-Mobile Version

3.2.0

### Device

Google Pixel 7

### Operating System Version

Android

### Device Locale

US 

### Selected Locale

None

### Additional Context

Happens on beta as well as stable android app store version.

**Comment by astubenbord** [comment] 2024-01-07 18:48
Closing as duplicate of #350

**Closed as completed by astubenbord** 2024-01-07 18:48 UTC
Labels: bug, duplicate
