### ISSUE TITLE
[BUG] Add tags instead of selecting input underneath

### ISSUE THREAD

**Issue by lennartbrandin** [astubenbord/paperless-mobile#140] opened 2023-03-13 16:01 UTC
**Describe the bug**
When adding/editing tags if you pick tags that are covering other input fields (Document type / Storage location) the tag menu closes and the input field is selected.

**To Reproduce**
1. Edit document.
2. Try to add tags

**Expected behavior**
The clicked tag is added to the document.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Device Information:**
 - Device: Nokia 8
 - OS: Android 9
 - Paperless Mobile version: 2.1.0 +27
 - Paperless Server version: 1.13.0 APIv2

**Comment by astubenbord** [comment] 2023-03-13 16:02
Closing as duplicate of #83, also see troubleshooting in Readme, thanks.

**Closed by astubenbord** 2023-03-13 16:02 UTC
Labels: bug
