### ISSUE TITLE
[BUG] Cannot search for a label in the "Filter Documents" view

### ISSUE THREAD

**Issue by SpicyWasab** [astubenbord/paperless-mobile#137] opened 2023-03-07 18:02 UTC
**Describe the bug**
On the main `Documents` tab, in the filter FAB's drawer there's a "label" view all the way down.
When clicking on it, there's a drop-down list with all the tags. Clicking on one of them is fine, but I can't search for one particular label and click on it. Searching for a label works, but when I click on the label it unfocuses the text-input as if the drop-down menu wasnt't there and I clicked behind it.

**To Reproduce**
1. Open the app
2. Click on the FAB in the top right corner.
3. Scroll down to the last text input for labels
4. Search for a label
5. Click on one of the results
6. See error

**Expected behavior**
We should be able to click on the label to apply it to the filter.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Device Information:**
 - Device: Samsung Galaxy A51
 - OS: Android 13
 - Paperless Mobile version 2.1.0+27
 - Paperless Server version 1.13.0 (API v2)

**Additional context**
Btw I just saw that you included my translations, thanks c:
I'm gonna do some edits later, since I quickly noticed that on the Scanner tab the "upload" button overflows. It still works but it's ugly.

**Comment by SpicyWasab** [comment] 2023-03-07 18:08
I just noticed that apparently it does the same for document types, but even if I didn't typed anything yet. I can't click on any document type in the dropdown.
I can't try for Correspondents and Storage Paths since they're greyed-out on my side.

**Comment by astubenbord** [comment] 2023-03-07 18:09
Closing as duplicate of #83, also see the Troubleshooting section in the Readme.

**Closed** 2023-03-07 18:09 UTC
Labels: bug

**Comment by SpicyWasab** [comment] 2023-03-07 18:20
Oh I see
I saw it in the Readme a week ago but I didn't remember.

Not sure if it's useful to say, but for the record I don't have bitwarden, I use keepass. It doesn't seem to be related.
In my case it was Bitdefender Mobile Security in the Accessibility Settings.

**Comment by astubenbord** [comment] 2023-03-13 13:32
No worries, it's not directly related to bitwarden but accessibility in general. I think I'll update the forms at some point to not be affected by accessibility settings, and there also seems to be a workaround by disabling accessibility navigation in the app. But for now this has to be fixed on the system side unfortunately.
