### ISSUE TITLE
Query for changes of last n days, weeks, month

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#53] opened 2022-12-14 17:38 UTC
If you set the filter to 'Last 7 days' your app creates a query with a start date 8 days ago and an end date of tomorrow. If you save that as a view, it will save the dates. If you recall that view tomorrow or even next week it will not return the documents of the last 7 days, but the documents of 7 day period in the past.

The paperless web ui sets the query param to 'added:[-1 week to now]' instead.

**Comment by astubenbord** [comment] 2022-12-15 20:32
Weird, I cannot reproduce this behavior. Is the "added:[-1 week to now]" also reflected in the filter rules property of the saved view?

Could you create a saved view with only "created" set to Last 7 days and provide the JSON representation of said view? (/api/saved_views/)

When I do this, as of today, the 15th December 2022, I get the filter rule with key 9 and value "08-12-2022". Key 9 corresponds to the "created date after" rule.

I'm on server version 1.9.2.

**Comment by astubenbord** [comment] 2022-12-15 22:13
Never mind my last comment, it appears there was an error in either my installation or the paperless version I was running. I updated to 1.10 and now it's working as you described.

**Comment by astubenbord** [comment] 2022-12-15 23:33
Apparently this syntax is just the tip of the iceberg, see https://whoosh.readthedocs.io/en/latest/dates.html#parsing-date-queries.

I guess implementing only the `<field>:<n> <unit> to now` syntax will have to do for now at least.

**Comment by steinm** [comment] 2022-12-16 15:59
Yes, that would be sufficient. In your app the buttons "Last 7 Days", "Last Month", etc. just have to trigger a search with the above syntax instead of setting the date selection field, which is probably easier said than implemented.

**Comment by astubenbord** [comment] 2022-12-31 01:01
Hi, I added this in the latest release. Feel free to check it out and give me some feedback!

**Comment by steinm** [comment] 2022-12-31 13:29
Seems to be working. Just one minor thing. If a stored view contains a filter for the last 7 days and you select that view and afterwards edit the filter settings, the query 'created:[-1 week to now] shows up in the 'title & content' field

**Comment by astubenbord** [comment] 2023-01-01 22:28
Yes, I found the issue. will update in the next days.

**Comment by astubenbord** [comment] 2023-01-05 13:08
There was another issue, when having both an extended query and a relative date range in specified in a view, the query was not correctly encoded. Will be fixed in 1.4.1

**Closed** 2023-01-11 17:42 UTC
Labels: enhancement
