### ISSUE TITLE
new Correspondent cannot get added

### ISSUE THREAD

**Issue by andreas-0001** [astubenbord/paperless-mobile#239] opened 2023-07-23 07:52 UTC
Hi everyone.
I am trying to add a Correspondent for a document but the respective Page remains empty. When doing same thing in the paperless-ngx web interface, it works.
Tested with a Google Pixel 7 pro running  Android 13 and paperless mobile Version 2.3.9+44 ( used with German User Interface) and paperless-ngx 1.14.5.

-Starting from documents view ( No Filter applied),
-View a document
-Edit the document
-Click in Correspondent selection Field
-Type a new Correspondent name
-->click to add a new Correspondent, a new Page opens, but it remains completely empty. 
Maybe I did mistake, anyhow I hope the description is clear and someone could help me with my isse.
Thanks

**Comment by astubenbord** [comment] 2023-07-23 09:32
Related to #233

**Comment by astubenbord** [comment] 2023-08-13 16:54
Closing as duplicate of #233

**Closed as completed by astubenbord** 2023-08-13 16:54 UTC
Labels: bug, duplicate
